server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://relay:3847/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    client_max_body_size 512m;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
  }

  location /blob/ {
    proxy_pass http://relay:3847/blob/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    client_max_body_size 512m;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
  }

  location /ws {
    proxy_pass http://relay:3847/ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
