export {
  encryptFileForSend,
  decryptFileFromChunks,
  encryptFileChunks,
  decryptChunk,
  assembleChunks,
  verifyChunkMerkle,
  encodeFileEnvelope,
  decodeFileEnvelope,
  encodeChunk,
  decodeChunk,
  DEFAULT_CHUNK_SIZE,
  type ChainLockFileSendResult,
  type ChainLockFileReceiveResult,
  type FileMetadata,
  type EncryptedChunk,
  type DecryptedChunk,
  type ChunkEncryptResult,
  type FileEnvelopeFields,
  type ChunkFields,
  type ChunkWithProof,
  type MerkleProofNode,
} from './envelope.js';
